### ISSUE TITLE
Typo readme

### ISSUE THREAD

**Issue by 1951FDG** [laysent/remark-lint-plugins#22]
I believe the quotes are missing for length, the following line works! This applies to config file!

```
["remark-lint-no-long-code", { "length": 100 }]
```

**Comment by laysent** [comment]
I have fixed this. Thanks a lot. (see: https://github.com/laysent/remark-lint-plugins/commit/a076450f4d4c515656292d216868a09d58cc2f07)

**Comment by 1951FDG** [comment]
Thank you!
